# Generated by Django 2.0 on 2019-06-17 13:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('reccomendation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('choice_1', 'Polecam!'), ('choice_2', 'Nie polecam')], max_length=17, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.ImageField(blank=True, default='blank.jpg', null=True, upload_to='')),
            ],
        ),
    ]
