# Generated by Django 2.0 on 2019-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.ImageField(blank=True, default='blank.jpg', null=True, upload_to='plakaty')),
            ],
        ),
    ]
