# Generated by Django 2.0 on 2019-06-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktor',
            name='filmy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Aktor',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
