# Generated by Django 2.0 on 2019-06-17 14:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='reccomendation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Polecam!'), (1, 'Odradzam!')], default='', max_length=3, null=True),
        ),
    ]
