# Generated by Django 2.0 on 2019-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190616_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
