# Generated by Django 2.0 on 2019-06-17 14:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190617_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='reccomendation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Polecam!'), (1, 'Odradzam!')], default='', max_length=3, null=True),
        ),
    ]
