# Generated by Django 2.0 on 2019-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190214_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Komedia'), (1, 'Horror'), (3, 'Sci-Fi'), (0, 'Nieznany'), (4, 'Dramat')], default=0),
        ),
    ]
