# Generated by Django 2.0 on 2019-06-19 14:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190619_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='reccomendation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Yes', 'Polecam!'), ('No', 'Odradzam!')], default='', max_length=6, null=True),
        ),
    ]
