# Generated by Django 2.0 on 2019-06-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190616_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.FileField(blank=True, default='blank.jpg', null=True, upload_to=''),
        ),
    ]
