# Generated by Django 2.0 on 2019-02-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190202_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=128)),
                ('nazwisko', models.CharField(max_length=128)),
                ('filmy', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Komedia'), (1, 'Horror'), (4, 'Dramat'), (3, 'Sci-Fi'), (0, 'Nieznany')], default=0),
        ),
    ]
