# Generated by Django 2.0 on 2019-02-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190202_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (4, 'Dramat'), (2, 'Komedia'), (0, 'Nieznany'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ExtraInfo'),
        ),
    ]
